services:
  db:
    image: postgres:alpine
    restart: always
    container_name: sdc-db_c
    environment:
      POSTGRES_USER: andyma
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: questionsandanswers
      PGDATA: /var/lib/postgresql/data/db-files/
      PGHBA_CONF_FILE : /etc/postgresql/pg_hba.conf
      POSTGRES_CONFIG_FILE : /etc/postgresql/postgresql.conf
    ports:
      - '5432:5432'
    volumes:
      - /home/ubuntu/SDC_CSV:/var/lib/postgresql/data/pgdata
      - /home/ubuntu/database/CreateQATables.sql:/docker-entrypoint-initdb.d/1-init.sql
      - /home/ubuntu/database/postgresql.conf:/etc/postgresql/postgresql.conf
      - /home/ubuntu/database/pg_hba.conf:/etc/postgresql/pg_hba.conf
~